name: CI for Go Code #Naming the workflows
on: #for event triggering
  push:
    branches: [main] #add more branch with a comma
  pull_request:
    branches: [main]
    
jobs: #jobs to exe
  build: #name of the job
    name: Load OS #name for printing
    runs-on: ubuntu-latest #specify os in virtual machine
    steps:
    - name: Print Hello
      run: | #run terminal command
        ls
        echo Hello!
    - name: Setup Go env
      uses: actions/setup-go@v3.2.0
      with:
        go-version: 1.18
    - name: Checking current version
      run: go version
